pipeline:
  build:
    image: python:3.7.4-alpine
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt
      - python setup.py install
      - python -m unittest tests